### PR TITLE
Talking Medbots!

### PR DESCRIPTION
**Pull request by Software-Pirate-Captain**
Changes some desctexts and makes Medbots talk to ya! They'll announce
aloud when they're approaching someone to give 'em the good stuff, and
will comment on the nature and severity of their injuries, where voice
line availability allows.

I have bigger plans than just this, including enabling them to comment
on major/minor fracture status and internal bleeding, as well as
advising their patient when they're gonna need a real doctor for THAT
boo-boo, and many of these may be tied in to an overhaul of
medbots in general. But, each big adventure has a first step, and I'm
happy with this in its own right.

### CODE REVIEW

**Comment by BillyBangles** [comment]
On a scale of 1 to 10 how sure are you that those voice lines aren't copyrighted?

**Comment by ghost** [comment]
I might prefer to see these as an upgraded medibot or more expensive 'advanced medibot' that can be constructed.

**Comment by Software-Pirate-Captain** [comment]
Goop, I've taken a quick look at some of the stuff around fair use and since it's a non-commercial use and we aren't harming the market for the original product, I doubt there'll be any issues.

Ursa, I have plans to eventually resprite medbots entirely and upgrade them, which can take the form of an "Advanced" version if you'd prefer. Something else that might be possible is to leave this basic medbot with only the ability to call out the basic 4 damage types, and then leave the advanced diagnostics, like broken bones and internal bleeding, to this hypothetical advanced medbot?

**Comment by BillyBangles** [comment]
I have two concerns.
1. The four damage types aren't terribly... realistic. If a doctor came up to you, waved an instrument around a bit, and shouted to his buddies, "He has sixty brute damage, get him on a stretcher!" you'd probably think he was a quack. Similarly, you might notice that the voice lines you added never say anything like, "User health at 40%." My recommendation for when you write out the diagnosis lines is to try to avoid numbers. For example if someone's got toxins at like, 10 or below, have it say like, "Minor Toxin content detected." or something. Hell, it'd be really neat if you were able to let the user change these thresholds, but that might be asking a bit much.

2. Tread lightly when you rework how medibots treat injuries, lest you put doctors, chemists, or surgeons out of a job.

**Comment by Software-Pirate-Captain** [comment]
I'm not entirely sure what you're talking about? The voice lines do indeed never mention numbers, and I'm not planning on adding any kind of paper printout, its speech _is_ the diagnosis.

What you're saying is entirely fair, but they never did that anyway, I'm not sure I understand how it applies to what I've done here?

As for reworking/upgrading them, that'll be a seperate pullreq for exactly that reason.

Anything else?

**Comment by BillyBangles** [comment]
I know the voice lines don't say numbers, I never said they did. In fact, I specifically said they don't. What I'm talking about is the lines that get printed out _in the game._ The text that shows up in the chat box. At least, I hope you intend to add in-game text to go along with these voice lines. Else people who don't play with sound on will have no idea what the medibot is saying. And I've looked at the code here, you haven't written any diagnosis text yet, so I'm not asking you to change anything right now. I'm just giving advice for the future.

**Comment by Software-Pirate-Captain** [comment]
...I wasn't, no, the entire point was to replace the in-game text with voice callouts. I mean I can do those too, and can bear what you've said in mind if that's a problem. I'll tackle that next.

**Comment by BillyBangles** [comment]
I personally tend to play without sound/headphones (my audio card is shit and doesn't like dream seeker for some reason) and i can almost guarantee you I'm not the only one.

**Comment by Software-Pirate-Captain** [comment]
Alright, I'll make that change either tonight or tomorrow. What prevents it from being pulled, its unfinished state, or is there another process that's left it sitting in limbo?

**Comment by BillyBangles** [comment]
Well, you seem to keep making commits, so yeah, I'm waiting for you to finish, pretty much.

**Comment by silveryferret** [comment]
this commit was so that I can look at it and figure out why sounds are playing when they shouldn't.

**Comment by Software-Pirate-Captain** [comment]
Alright. I think that's everything I want to put forward for this pullreq, I've made all the changes in this difficulty bracket. Is it acceptable for you guys?

**Pull request merged**
