### PR TITLE
A few minor fixes.

### PR DESCRIPTION
**Pull request by Faire-Fuzzy**
Fixed a minor icon issue with the fem Scorpius bot body and made a few
of necklaces/collars wearable in the mask slot so they don't get in the way of lewd bits, like breasts. As well as actaully giving the rosary a worn sprite.

### CODE REVIEW

**Comment by silveryferret** [comment]
you could also add "show_genitals = 1" if all you want is to make them not hide naughtybits. I believe. I'll need to double check just to make sure.

**Comment by Faire-Fuzzy** [comment]
Can you? I didn't know if that could be applied to accessories like that.

**Comment by silveryferret** [comment]
You can, yes. Here's an example. https://github.com/ErosResearchPlatform/Eros/blob/9045ed30ef456cd30a8bf8d0355e8567135490c3/code/modules/eros/clothing/accessory.dm#L238

**Comment by Faire-Fuzzy** [comment]
Hmm, I'll just do that then I guess, I'll probably have the revised pr by tonight.

**Pull request closed without merging**
