### PR TITLE
Runtime fix

### PR DESCRIPTION
**Pull request by Mewchild**
Changes indicator for bold from * to +

### CODE REVIEW

**Comment by Mewchild** [comment]
[text emphasis runtime](https://trello.com/c/JiHXoKUu/23-text-emphasis-runtime)

**Comment by Mewchild** [comment]
[text emphasis runtime](https://trello.com/c/JiHXoKUu/23-text-emphasis-runtime)

**Comment by Mewchild** [comment]
[text emphasis runtime](https://trello.com/c/JiHXoKUu/23-text-emphasis-runtime)

**Comment by Mewchild** [comment]
[text emphasis runtime](https://trello.com/c/JiHXoKUu/23-text-emphasis-runtime)

**Comment by Mewchild** [comment]
[text emphasis runtime](https://trello.com/c/JiHXoKUu/23-text-emphasis-runtime)

**Comment by Mewchild** [comment]
[text emphasis runtime](https://trello.com/c/JiHXoKUu/23-text-emphasis-runtime)

**Comment by Mewchild** [comment]
[text emphasis runtime](https://trello.com/c/JiHXoKUu/23-text-emphasis-runtime)

**Comment by Mewchild** [comment]
[text emphasis runtime](https://trello.com/c/JiHXoKUu/23-text-emphasis-runtime)

**Comment by Mewchild** [comment]
[text emphasis runtime](https://trello.com/c/JiHXoKUu/23-text-emphasis-runtime)

**Comment by Mewchild** [comment]
[text emphasis runtime](https://trello.com/c/JiHXoKUu/23-text-emphasis-runtime)

**Comment by Mewchild** [comment]
[text emphasis runtime](https://trello.com/c/JiHXoKUu/23-text-emphasis-runtime)

**Comment by Mewchild** [comment]
[text emphasis runtime](https://trello.com/c/JiHXoKUu/23-text-emphasis-runtime)

**Comment by ursamedium** [comment]
[text emphasis runtime](https://trello.com/c/JiHXoKUu/23-text-emphasis-bugfix)

**Pull request merged**
