### PR TITLE
Consistently Purple Phoron

### PR DESCRIPTION
**Pull request by ghost**
Makes phoron and phoron accessories purple.

Sprites sourced from @chaoko99's Baystation12/Baystation12#16648 -- I added hazard stripes to the little tank, too. Thanks, dude. Purple phoron's my jam. Grape jam. I guess.

Some code and orange xenoarch crystal sourced from Baystation12/Baystation12#16662 , but we're staying purple.

### CODE REVIEW

**Comment by chaoko99** [comment]
👍

**Comment by chaoko99** [comment]
[You know it.](https://www.youtube.com/watch?v=oag2uZcNNxE)

**Comment by silveryferret** [comment]
Hi Bear. Can you go peek through those conflicts and resolve 'em please? WE just did a big merge from Baystation and I wanted to merge that first for exactly this reason. Thanks.

**Comment by chaoko99** [comment]
Oh, those conflicts are actually due to my having gone the OTHER direction. Pff. Still appreciate your having taken the purple. Phoron is my jam, and grape jam is the best one.

I just scrolled up and realized you used this pun. Dammit.

**Comment by silveryferret** [comment]
Yeah, the conflict is why I wanted to merge from you guys first, otherwise it was just going to override the purple that we put in with the orange... and then we'd have to go back and do that again...

**Comment by ghost** [comment]
:ok_hand:

**Pull request merged**
