### PR TITLE
Collective of Things

### PR DESCRIPTION
**Pull request by ghost**
A collective of some changes and additions, because I appear to be incapable of producing work in individual, neat PRs, and instead do these clusterfucks.

Following = Port from Polaris:
- The ability to empty ashtrays into disposals. They are able to be thrown in the disposals chute after they are empty.
Also, all ashtrays now hold a max of six cigarettes, no matter what material.
- Nurse spiders properly give a notification when they inject eggs into a limb.

Borg + AI Additions:
- New sprite choices for borgs. Mostly sourced from Aurorastation, /vg/station, tgstation, Paradise. Astromech sprite by Nienhaus.
borg
- New hologram choices for AI.  New malf-only hologram choices.
Holograms
Malf-only
- New AI core icons, and death state icons for some existing icons. Seventeen new ones, I believe?

Sprite changes:
- New sprites for t-ray scanner, eftpos, forensic scanner, plant analyzer (and it animates when it scans a plant), cautery, hemostat, retractor, and robot analyzer. From Eris and tg, attention drawn to them from, PolarisSS13/Polaris#3070
sprites
Thoughts?

Also, I can't figure out which borg is missing eyes. :question:

### CODE REVIEW

**Comment by ghost** [comment]
👀 ok travis thanks i'll find the missing eyes later.

**Comment by RemieRichards** [comment]
My panda eggs!

**Comment by ghost** [comment]
@RemieRichards I love the panda eggs very much.

**Comment by ghost** [comment]
AI-Soviet is a duplicate of AI-Redoctober.

**Pull request merged**
